export const DEFAULT_THEME_CONFIG = {
  global: {},
  local: {}
};

export const KUI_THEME_USER_CONFIG = 'KUI_THEME_USER_CONFIG';

export const KUI_THEME_PREVIEW_CONFIG = 'KUI_THEME_PREVIEW_CONFIG';

export const ACTION_DOWNLOAD_THEME = 'KUI_THEME_ACTION_DOWNLOAD';

export const ACTION_APPLY_THEME = 'KUI_THEME_ACTION_ALLPY_CSS';

export const ACTION_COMPONECT_SELECT = 'KUI_THEME_ACTION_COMPONECT_SELECT';

export const ACTION_USER_CONFIG_UPDATE = 'KUI_THEME_USER_CONFIG_UPDATE';
